name: Staging Deploy

on: deployment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.deployment.environment == 'staging' && startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
      - name: Use Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Build
        run: yarn staging:build
      - name: Deploy to Kubernetes Cluster
        run: echo ${{ github.ref }} ${{ github.event.deployment.environment }} ${{ github.event.deployment.id }}
      - name: Mark Deployment Success on GitHub
        run: |
          curl --location --request POST 'https://api.github.com/repos/kamleshchandnani/rabbit-hole-github-actions/deployments/${{ github.event.deployment.id }}/statuses' \
          --header 'Authorization: token ${{ github.token }}' \
          --header 'Accept: application/vnd.github.everest-preview+json' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "environment": "staging",
            "state": "success"
          }'
